### ISSUE TITLE
Internal Scheduler sometimes fails

### ISSUE THREAD

**Issue by BladeofRagna** [xlash123/KHUx-Discord-Bot#14]
Not entirely sure what's going on, but I've attempted to have the bot set NA tweets in my server, but the bot isn't ever posting them now. I've made sure moments before the tweets go out to have them set to on, but it still doesn't post them. It may be a legit bug, or it's something on my end. Just not sure what to do.

**Comment by xlash123** [comment]
The tweet didn't post for me tonight, so I'm certain part of it is the bot's fault. I'll see what is wrong and do some extensive testing.

**Comment by BladeofRagna** [comment]
Update: Lux reminders are also not going off. Had them set for last night and kept the bot running overnight. No reminders were made despite the fact that NA lux reminders are already on.

**Comment by xlash123** [comment]
Restart the bot and double check it's enabled.

**Comment by xlash123** [comment]
I'm experiencing issues with it as well. I'm theorizing that the internal Scheduler has failed somehow, so I've renamed the issue to reflect that, especially since it has affected both Twitter updates and lux reminders.

If I had a dollar for every time I thought I fixed this...

**Comment by Lexycon94** [comment]
If I may add my data to the issue, it seems that it only does the reminder for the first bonus hour that it's turned on for

**Comment by xlash123** [comment]
As a temporary fix, restart the bot and re enable lux times. It fixed everything for me. I believe this is a kind of issue that appears the longer the bot is online.

**Comment by bree-is-bree** [comment]
The Amazon hosted bot seems to be having these issues as well, at least for our server. It'll fetch medal info, but will not get tweets or send out lux reminders.

**Comment by Lexycon94** [comment]
On my server, all the lux reminders work, but we haven't got a tweet

**Comment by xlash123** [comment]
I haven't seen this issues. Are you sure you've enabled lux reminders and Twitter updates? If so, this doesn't seem like a Scheduler issues since everything is running when it's supposed to. Likely, something is preventing it from sending to your channels.

**Comment by Lexycon94** [comment]
Whoops, yea I forgot to turn tweets on. I have been having 0 issues with
the amazon hosted version

**Comment by bree-is-bree** [comment]
I have tried to enable lux reminders with the !lux on command, no response. I've also had twitter updates on, and it hasn't fetched any tweets. 

If it matters, when manually hosting the bot, it does all of its functions properly. So that's likely what I'll stick with until the Amazon one stops being weird.

**Comment by xlash123** [comment]
@DaltonUX Contact me on Discord. My tag is #Xlash4351. It seems like it's just your server that's affected. I should be able to work it out if I discuss some stuff with you.

**Comment by xlash123** [comment]
No issues on the bot end. Likely the feature just needs to be enabled or the bot needs permission to post on that channel.
