### ISSUE TITLE
Tweet Issue

### ISSUE THREAD

**Issue by KyetoJ** [xlash123/KHUx-Discord-Bot#18]
Hey man, just noticed you updated the hosted bot a little while ago and noticed that with you try to get the latest tweet it comes up with a link that doesnt connect to anything. I think its cause you included twitter.com twice. Heres what it posts:  https://twitter.com/https://twitter.com/kh_ux_na/status/898741310521298945
This happened for both NA and JP tweets. Hope this is a simply issue to fix, Anyway, thanks for making an awesome bot and looking forward to future updates!

**Comment by xlash123** [comment]
Yep. Haha. That's what happens when you make a small change and don't test it. I will fix this ASAP.

**Comment by KyetoJ** [comment]
Thanks dude! Glad it wasnt my server that broke it XD

**Comment by xlash123** [comment]
Resolved
