### ISSUE TITLE
double lux scheduling

### ISSUE THREAD

**Issue by revolverinebat** [xlash123/KHUx-Discord-Bot#20]
is there a way to edit the bot's code so it can notify the double lux time 5 minutes in advance? thanks in advance!

**Comment by xlash123** [comment]
Yes. I can make a configurable setting for it.

**Comment by revolverinebat** [comment]
will you? do you mind... Please let me know, kind sir! Also, thank you once again. Helpful bot to say the least

**Comment by xlash123** [comment]
Added in 1.5.0
