### ISSUE TITLE
Saix name issue

### ISSUE THREAD

**Issue by shanible** [xlash123/KHUx-Discord-Bot#24]
The bot doesn’t seem to recognize “Saix” as a medal. When “Saïx” is used, Saïx B comes up. Just thought you should know!

**Comment by shanible** [comment]
Also, the nickname KEX doesn't work for Kairi EX. Neither does iTerra.

**Comment by xlash123** [comment]
This issue is one that stems deep into my search algorithm. I’ve been meaning to redo it so that it actually, you know, works. For now, the best way to get a medals info is to enter its name exactly as it appears on the KHUx wiki.

**Comment by shanible** [comment]
No worries. I realized iTerra was my bad. I had to specify with the bot either iTerra A or iTerra B.

**Comment by xlash123** [comment]
Resolved due to overhaul of the medal system.
