### ISSUE TITLE
"Bad Authentication Data"

### ISSUE THREAD

**Issue by BladeofRagna** [xlash123/KHUx-Discord-Bot#25]
Just downloaded the new update for the bot and can't get it to launch. May be a similar issue from previous issues, though after taking a screenshot to get a look at the bot before it forces itself to close, there's one line that reads "Bad Authentication Data" under a line with an httpResponseImpl.

[https://gyazo.com/0a63354fd518dd4643839c8779da9e1b](url) Here's a link for the full screenshot. Hoping this isn't a major issue and I'm just an idiot. XD (I do have my Java updated with no other previous versions installed in case that may have been the issue)

**Comment by xlash123** [comment]
Yeah... I haven’t updated the readme for this yet, but the last update switched the bot over to using the Twitter API, which requires that you create an app with them and then use the authentication tokens within your Twitter app to allow the bot to use the Twitter API. I really wish that wasn’t the case, but I have it all set up with my host, so I highly recommend switching over, unless you don’t mind setting it up yourself.

**Comment by BladeofRagna** [comment]
If I could figure out how to do that I would. Guess I'll just have to use the host then.

**Comment by xlash123** [comment]
I've decided that having the Twitter API isn't worth it if it means people can't self host, so I've removed it in 1.5.3 and will now no longer give this error.
