### ISSUE TITLE
Issue with Gauge Information

### ISSUE THREAD

**Issue by elvis-github** [xlash123/KHUx-Discord-Bot#26]
With the new bot update, my party and I noticed that the gauge information is inaccurate and only reports with a 0. I believe this could be due to gauge being misspelled as guage. 

![boop](https://user-images.githubusercontent.com/35156652/34635164-a1ad2ae2-f259-11e7-8071-de5d77da80ae.PNG)
![2](https://user-images.githubusercontent.com/35156652/34635166-a5575352-f259-11e7-985e-72813f447fab.PNG)
![1](https://user-images.githubusercontent.com/35156652/34635167-a6df1642-f259-11e7-851a-1798792a0021.PNG)

**Comment by xlash123** [comment]
Yessir. I realized that myself, and it is now fixed in version 1.6.1.
