### ISSUE TITLE
I'm admin, but "Only admins may use this command".

### ISSUE THREAD

**Issue by Fieralegion** [xlash123/KHUx-Discord-Bot#27]
Hi xlash123, I use the application recently, but I think it's great. However, I have a problem and I don't know  why.
I'm the admin on the server, but when I use !admin, !default or !config, appears the message: 
"Only admins may use this command".
Command !medal works fine, by the way.

I have read all the guides I found about the bot, but I can't find anything. Any idea what the problem might be?

Thanks for the bot!

**Comment by xlash123** [comment]
By admin on the server, do you mean you've been set as admin using the `!admin` command or you are a admin through server permissions?

**Comment by Fieralegion** [comment]
I mean that I created the server, so I have all the permissions. KHUX bot works fine with !medal, but with !medal, !admin, !config, !lux, or any other, KHUX bot tell me: "Only admins may use this command".

**Comment by xlash123** [comment]
Even if you created the server, the bot doesn't know that. You'll need to have the Administrator permission checked in a role for the bot to know. Once you do that, you can use !admin to admin yourself and others. Afterwards, the bot will know you are an admin without the actual Discord permission.

Let me know if this fixes it, and sorry for the late response.

**Comment by xlash123** [comment]
I just released update 1.8.0 in which I resolved some errors with the !admin command. I believe this issue has been resolved. Let me know if otherwise.
