### ISSUE TITLE
Commands Involving Medals Do Nothing

### ISSUE THREAD

**Issue by bree-is-bree** [xlash123/KHUx-Discord-Bot#28]
When looking up a medal using !medal, !medalna, or !medaljp, the bot does not respond at all. This is also the case for the !medallist command. Commands, such as !tweet work just fine, however.

I should also point out that this occurs both when manually hosting the bot and using the Amazon hosted one.

**Comment by xlash123** [comment]
I've just noticed the issue, and I will get to fixing this ASAP.

**Comment by xlash123** [comment]
Fixed in 1.6.3. Thanks for letting me know.
