### ISSUE TITLE
Lux times aren't displaying

### ISSUE THREAD

**Issue by Lexycon94** [xlash123/KHUx-Discord-Bot#29]
Hello,
I have invited the bot that you are hosting. The issue is that, while the timer seems to be working fine (!lux check gives the right time left) the bot does not actually post when the lux hour starts. Friends are having this issue in other servers.

**Comment by xlash123** [comment]
I will look into this.

**Comment by Lexycon94** [comment]
Thank you so much! You don't know how much my party relies on your bot. It's so good and I'm so happy that you've been working so hard on it and updating it!

**Comment by xlash123** [comment]
I can confirm bug, yet don’t know why it’s happening. I will be able to research this tonight.

**Comment by xlash123** [comment]
Simply restarting the instance seemed to do it. I'll close this issue, but if it comes back up again, I'll reopen this.
