### ISSUE TITLE
Lux/UC alerts not working

### ISSUE THREAD

**Issue by alphearia** [xlash123/KHUx-Discord-Bot#35]
I've noticed for the past few months, the UC and Lux alerts for both NA and JP haven't been working on any server I have the bot in.

**Comment by xlash123** [comment]
Have you confirmed that the bot has permissions to post in your channels? Because I've been using them on my server with no issues at all.

**Comment by xlash123** [comment]
Actually, I believe this falls into another issue (I've just now determined its existence). Please follow issue #33 for updates on this.
