### ISSUE TITLE
Feature request: admin-only permissions?

### ISSUE THREAD

**Issue by ghost** [xlash123/KHUx-Discord-Bot#4]
Currently, anyone can use the `!lux` and `!tweet` commands. This causes a bit of spam and it's frustrating to set permissions and not have anyone mess with them. Is it possible to make these commands only available to only server administrators?

**Comment by xlash123** [comment]
Yeah. I've starting working on the foundations for this. Expect it soon.

**Comment by xlash123** [comment]
Added in version 1.2.3
