### ISSUE TITLE
! command not responding

### ISSUE THREAD

**Issue by SaltCrowns** [xlash123/KHUx-Discord-Bot#43]
I've given the bot admin permissions and everything but I'd say around late October, the !salt, !tweet and !medal command doesn't seem to work anymore. fortunately we still receive the alerts just fine, so I let it be. but now I'm getting some feedback from players about wanting to see the medals. so i wonder what occurred? what should i try out?

**Comment by xlash123** [comment]
I am looking into this issue.

**Comment by xlash123** [comment]
The issue seems only to be related to servers. To continue using functionality until the fix, try DM'ing the bot.

**Comment by xlash123** [comment]
All done! If you're still experiencing issues, make sure that the bot has Discord permissions to post in the channels it needs to. Giving the bot admin permissions is not necessary and is discouraged.
