### ISSUE TITLE
The Bot went offline

### ISSUE THREAD

**Issue by AfricanPanda** [xlash123/KHUx-Discord-Bot#46]
Hey so, I’ve been using your KHUX bot and it’s been a major help for my clan, but now it has went offline. Is this because if something I did on my end or yours? Hopefully you’ll respond to this

**Comment by xlash123** [comment]
Thanks for your concern. However, for the time being, I will be terminating service for the bot. For a long time now, I, as well as the creator of the database I use, have been inactive within the KHUx community. So the bot has been out of date with the various new medals obtainable now. Also, I have been hosting the bot for quite some time by myself, and it's become harder to justify paying the fee to host it when the utility of the bot is diminishing.

However, I might try in the future to make some changes and find an alternative database as to revive the bot. I know that many people still use the bot, and I don't want it to stay down forever. But for now, if you wish to use the functionality, you'll have to resort to self-hosting.

Edit: Just thought I should clarify that I have backed-up all important configuration data, so if the bot does get revived, no reconfiguration should be necessary.
