### ISSUE TITLE
Allow lighter permissions?

### ISSUE THREAD

**Issue by TehPower** [xlash123/KHUx-Discord-Bot#5]
The most recent update made it so only admins can change settings. Maybe have it configurable in the config file?

**Comment by xlash123** [comment]
Sure. Just a question: would you rather have that set by command or by role?

**Comment by Lexycon94** [comment]
Just chiming in, since I am running the bot for my server but am not admin, it would be nice to be able to set custom roles in the config file for each command.

edit: rereading your response, personally I would appreciate if you could set it by command, and if it could work with custom roles as well.

**Comment by TehPower** [comment]
I'm not sure what you mean by have it set by command or role, but basically I'm hosting the server for my party's discord server but can't do any of the setting commands since I'm not the admin of the discord server (server admin is kinda not super present so it'd be nice not to have to go through him to get stuff done).

**Comment by xlash123** [comment]
If I do set by command, you could do something like !admin [username] to make someone admin. By role, you could create a role "Bot Admin", which will allow a user to admin the bot. I can do either one. The benefit of command is that you could make edits in the config, so you could get around the server admin not showing up. The benefit for role is being able to see who has the power over the bot via the user list.

**Comment by Lexycon94** [comment]
The first option sounds more versatile for the owner of the bot, and you can achieve the same effect as the "by role" with some smoke and mirrors (make a custom role and manage it manually by user in the config). I would say to it by command

**Comment by TehPower** [comment]
By command does seem the more versatile option

**Comment by xlash123** [comment]
I'll do that then. Thanks

**Comment by xlash123** [comment]
Forgot to close.
Added in 1.3
