### ISSUE TITLE
Searching names like Naminé and such don't work without the accents?

### ISSUE THREAD

**Issue by KoalaBe** [xlash123/KHUx-Discord-Bot#6]
Not sure if it's just me but I think since the update in nicknames we haven't been able to search "Namine" without getting an "I don't know..." I believe the same goes for the other accent marked names. I see it's still the in the code but for some reason it just won't find the medals unless you accent them.

**Comment by xlash123** [comment]
Yep. I think I saved the file in the wrong text format and it changed the accented e to some two weird characters. I'll fix that

**Comment by xlash123** [comment]
Resolved in 1.2.5
