### ISSUE TITLE
[Request] !medallist command

### ISSUE THREAD

**Issue by SvardXI** [xlash123/KHUx-Discord-Bot#7]
A command that lists all medals by name. If possible, maybe even make it possible to list medals by set, or by a keyword. Also giving NA and JP sepcific commands. So a couple examples would be:

!medallistjp
(lists all JP medals)

!medallistna set4
(lists all medals from NA Set 4)

!medallistjp Sora
(lists all JP medals containing the word, "Sora")

If possible, too, maybe make it so that !medallist by itself (e.g. without set numbers or keywords) can be disabled. That way, admins can keep users from flooding the channel multiple times with the full list, but still allow list lookups from a set or with a particular keyword.

**Comment by xlash123** [comment]
I wanted to implement a command like this for a while, but the spam it would cause would be insane. An idea I've had would be to link it to a text file that would contain all the medal and their nicknames

**Comment by SvardXI** [comment]
Why not just add a keyword lookup then? That way it keeps lists small. And if it becomes a problem for some servers, then all the admin(s) have to do is designate a specific channel for it, or disable the command altogether. I know it would be extra work, but you could also implement a timer system that allows for no more than X queries per X minutes, with parameters assignable by the admin(s).

**Comment by KW29** [comment]
How about just have the bot privately send whoever requested the list a PM with the list, that should prevent anyone from flooding the channel

**Comment by xlash123** [comment]
In the next version, this will be in. The current way it's implemented is it will PM you with the complete list of medals. This will eventually be something I remove in place of a better system as the list is really large and hard to quickly search through, but it'll get the job done.

**Comment by xlash123** [comment]
Forgot to close.
Added in 1.3
