### ISSUE TITLE
[Request] !lux check and set command

### ISSUE THREAD

**Issue by KyetoJ** [xlash123/KHUx-Discord-Bot#9]
Hi, sorry to bother but I was wondering and hoping if you would be able to put in a lux check command as in when you type in "!lux check" it would say how long until the double lux time. Ive had a slightly confusing time on my end trying to get the reminders to work as they didnt run at the time I thought they should have (however i think it was because I had set the default type to JP) but I just feel like having a check command would also be useful. Also if it would be possible to set a lux time as well, as ive just had the alert come up about an hour ago however this isnt the time thats normally used for my party at least. I just think it would be awesome if we could set it to run at specific lux times. So something kinda like "!lux set time1" which would set it to the one that just happened. And then 2 and 3 would be the later ones. Anyway sorry for disturbing again, these are just the thoughts ive been having. Thanks in advance!

**Comment by xlash123** [comment]
My bad on the times. I looked back and saw I had it completely wrong. I've fixed it in 1.2.5. As for the suggestions, I'll try to implement it in the next version.

**Comment by Lexycon94** [comment]
I experienced an issue with the bot not reporting the second bonus hour (8 am), though it worked fine on the 2 am one.

**Comment by bree-is-bree** [comment]
I can second what NickEscla said. For some reason, even with lux reminders enabled, the bot doesn't want to announce the bonus hours. He has done this with 11a.m. Eastern, as well as 5p.m. Eastern.

**Comment by xlash123** [comment]
It was working fine in my development environment, but I also noticed it not reporting lux times. In fact, the log said it failed to enable it. I'll try to put out a fix tonight.

**Comment by Lexycon94** [comment]
I got 1.2.6 and it just missed the 8pm bonus hour just now

**Comment by bree-is-bree** [comment]
That's odd, because the bot sent out the notification just fine for me.

**Comment by xlash123** [comment]
Was lux enabled @NickEscla ?

**Comment by Lexycon94** [comment]
Yes, I double checked right before. I can send you some logs

**Comment by xlash123** [comment]
It worked for me and it worked for the other guy, so give it a day. If it doesn't work again, I'll look into it. Also confirm that NA is the one being turned on, although I bet you have already.

**Comment by Lexycon94** [comment]
Turning lux reminders off and on again fixed the issue as far as I can tell

**Comment by NickEscla** [comment]
Turning lux reminders off and on again fixed the issue as far as I can tell

**Comment by Lexycon94** [comment]
The bot never posted about the end of bonus hour, and then never posted about the 2 pm bonus hour... Not sure what's going on on my side. I think only the first notice goes through

**Comment by shanible** [comment]
I agree with the OP about having different options for specific lux times. I'd like to take it a little further and be able to have each time reminder have a set channel option with their own custom message. Like suggested, maybe call them time1, time2, etc with the times attached to each a specific bonus time. That way, we set which ones we want on, where they post and what message goes with that time.

**Comment by xlash123** [comment]
I'm creating an issue for lux times not working. Please use that thead for that issue.

**Comment by xlash123** [comment]
As for the suggestion, I agree. I'll get to working on it

**Comment by xlash123** [comment]
Added the check feature in 1.5.0. I don't think the set feature is necessary, but if you feel it really should be implemented, let me know.

**Comment by xlash123** [comment]
In 1.8.0, I added the ability to select at which times you want the alerts to go off, which is basically the set feature that was described here, although it works through a menu that appears when running !lux on. Just in case anyone is still following this thread, now you know!
